import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

/**
 * Which operations validate a nonce, taken from the server's own .env.
 *
 * The client has to know, because an operation the server is not checking
 * should travel as a plain request rather than an envelope sealed with a
 * nonce nobody will look at. It could ask the server at runtime, but that
 * would mean publishing a list of unprotected operations to anyone watching
 * the network panel - so the answer is baked in at build time instead, from
 * the one file that already holds it.
 *
 * Only this key is read. Nothing else from server/.env comes near the bundle.
 */
function nonceEnabledOperations(mode: string): string | undefined {
  const serverEnv = loadEnv(mode, path.resolve(__dirname, '../server'), '');

  return serverEnv.NONCE_ENABLED_OPERATIONS;
}

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  plugins: [
    // babel-plugin-relay rewrites the graphql`` tags into requires of the
    // artifacts generated by relay-compiler into src/__generated__
    react({
      babel: {
        plugins: [['relay', { artifactDirectory: './src/__generated__' }]],
      },
    }),
  ],
  server: {
    port: 3000,
    strictPort: false,
    proxy: {
      '/graphql': {
        target: 'http://localhost:4000',
        changeOrigin: true,
        secure: false,
      },
      '/api': {
        target: 'http://localhost:4000',
        changeOrigin: true,
        secure: false,
      },
    },
  },
  build: {
    outDir: 'dist',
    sourcemap: true,
    // esbuild is Vite's default minifier and needs no extra dependency
    minify: 'esbuild',
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  define: {
    // `undefined` when the server sets no such variable, which is what tells
    // the client "everything is protected" rather than "nothing is"
    'import.meta.env.VITE_NONCE_ENABLED_OPERATIONS': JSON.stringify(
      nonceEnabledOperations(mode)
    ),
  },
}));
