import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    // babel-plugin-relay rewrites the graphql`` tags into requires of the
    // artifacts generated by relay-compiler into src/__generated__
    react({
      babel: {
        plugins: [['relay', { artifactDirectory: './src/__generated__' }]],
      },
    }),
  ],
  server: {
    port: 3000,
    strictPort: false,
    proxy: {
      '/graphql': {
        target: 'http://localhost:4000',
        changeOrigin: true,
        secure: false,
      },
      '/api': {
        target: 'http://localhost:4000',
        changeOrigin: true,
        secure: false,
      },
    },
  },
  build: {
    outDir: 'dist',
    sourcemap: true,
    // esbuild is Vite's default minifier and needs no extra dependency
    minify: 'esbuild',
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
